version = 1
disable_existing_loggers = false
log_file_path = "$HOME/Logs"

[root]
level = "NOTSET"
handlers = [ "debugconsole", "debug_file_handler",]

[formatters.none]
format = "%(message)s"

[formatters.msg]
format = "%(asctime)s - MESSAGE: %(message)s"

[formatters.simple]
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[formatters.extra]
format = "%(asctime)-16s %(name)-8s %(filename)-12s %(lineno)-6s %(funcName)-30s %(levelname)-8s %(message)s"
datefmt = "%m-%d %H:%M:%S"

[handlers.console]
class = "logging.StreamHandler"
level = "NOTSET"
formatter = "none"
stream = "ext://sys.stdout"

[handlers.message]
class = "logging.StreamHandler"
level = "INFO"
formatter = "msg"
stream = "ext://sys.stdout"

[handlers.debugconsole]
class = "logging.StreamHandler"
level = "NOTSET"
formatter = "simple"
stream = "ext://sys.stderr"

[handlers.debug_file_handler]
class = "logging.handlers.RotatingFileHandler"
level = "NOTSET"
formatter = "extra"
filename = "<replaceMe>.log"
maxBytes = 1048576
backupCount = 3
encoding = "utf8"

[handlers.error_file_handler]
class = "logging.handlers.RotatingFileHandler"
level = "ERROR"
formatter = "extra"
filename = "<replaceMe>_errors.log"
maxBytes = 1048576
backupCount = 3
encoding = "utf8"

[loggers."Debug  Logger"]
level = "NOTSET"
# handlers = [ "debugconsole", "debug_file_handler",]
handlers = [ "debug_file_handler",]
propagate = false

[loggers.ConsoleLogger]
level = "NOTSET"
handlers = [ "console", "debug_file_handler",]
propagate = false

[loggers.MessageLogger]
level = "NOTSET"
handlers = [ "message", "debug_file_handler",]
propagate = false
